print('====== Desafio 02 ======')
dia = input('Em que dia você nasceu?\nResp: ')
mes = input('Em qual mês você nasceu?\nResp: ')
ano = input('Em qual ano você nasceu?\nResp: ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano,'. Correto?')
